name: CI

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install toolchain (g++, cmake)  # ubuntu-latest มีอยู่แล้ว ส่วนนี้เพื่อความชัวร์
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake

      - name: Configure
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release -j 2

      - name: Run Unit Tests (ctest)
        run: ctest --test-dir build --output-on-failure

      - name: Smoke run app
        run: ./build/order_app
